### ISSUE TITLE
Azure Automation Limits

### ISSUE THREAD

**Issue by jasonvriends** [dawlysd/azure-update-management-with-tags#4]
My understanding is that Azure Automation can only execute 200 jobs at a time. If most of our VMs are scheduled for the same date/time, what would happen if we exceed that limit (i.e. would they be queued or fail). I am concerned that having X number of VMs all with schedules at the same date/time would hit this limit but not certain.

**Comment by davidsntg** [comment]
Correct, based on [automation account limit](https://github.com/MicrosoftDocs/azure-docs/blob/main/includes/azure-automation-service-limits.md), if more than 200 VMs need to be patched, they will be queued as long as the maintenance window is not exceed.
